version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run:
          command: echo "Hello World"

  cron-build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  build:
    jobs:
      - build

  e2e-test:
    jobs:
      - cron-build
    triggers:
      - schedule:
          cron: '* * * * *'
